# Generated by Django 5.0.4 on 2024-05-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("company", models.CharField(max_length=150)),
                ("year", models.IntegerField()),
                ("price", models.IntegerField()),
                ("image", models.ImageField(upload_to="cars")),
            ],
            options={
                "db_table": "Cars",
            },
        ),
    ]
